/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-container": "#0f2e2a",
        "surface-dim": "#dadada",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-container": "#3e2219",
        "surface-tint": "#46645f",
        "background": "#f9f9f9",
        "on-secondary-fixed-variant": "#3d4947",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#2e150c",
        "secondary-fixed": "#d9e5e2",
        "inverse-primary": "#adcdc7",
        "primary-fixed": "#c8e9e3",
        "on-secondary-container": "#596562",
        "on-surface": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "secondary": "#55615e",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbd0",
        "outline-variant": "#c1c8c6",
        "on-primary-fixed-variant": "#2e4c48",
        "surface": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "inverse-surface": "#2f3131",
        "on-tertiary-container": "#b1877a",
        "primary-fixed-dim": "#adcdc7",
        "secondary-container": "#d6e2df",
        "primary": "#001915",
        "on-surface-variant": "#414847",
        "surface-container-high": "#e8e8e8",
        "on-primary-container": "#779691",
        "surface-variant": "#e2e2e2",
        "on-secondary-fixed": "#131e1c",
        "on-primary": "#ffffff",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f3",
        "secondary-fixed-dim": "#bdc9c6",
        "tertiary-fixed-dim": "#ebbcae",
        "on-tertiary-fixed-variant": "#603f34",
        "outline": "#717977",
        "error": "#ba1a1a",
        "on-background": "#1a1c1c",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00201c",
        "tertiary": "#260e07"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "serif": ["Noto Serif", "serif"],
        "sans": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
}
